# Generated by Django 3.1.6 on 2021-02-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payharvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amount', models.CharField(max_length=255)),
                ('farmercode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.regfarmer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.CharField(max_length=255)),
                ('farmercode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.regfarmer')),
            ],
        ),
    ]
