# Generated by Django 3.1.6 on 2021-02-17 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_loan_payharvest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurancetype', models.CharField(choices=[('imyaka15', 'imyaka15'), ('imyaka10', 'imyaka10'), ('imyaka itanu', 'imyaka itanu'), ('umwaka umwe', 'umwaka umwe')], max_length=255)),
                ('farmercode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.regfarmer')),
            ],
        ),
    ]
