# Generated by Django 3.1.6 on 2021-02-18 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrecord',
            name='usered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cooperative'),
        ),
    ]
