# Generated by Django 3.1.6 on 2021-02-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210218_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestrecord',
            name='usered',
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='farmercode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.regfarmer'),
        ),
    ]
