# Generated by Django 3.1.6 on 2021-03-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210218_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointAfripay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('transaction_ref', models.CharField(max_length=234)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=234)),
                ('payment_method', models.CharField(max_length=234)),
                ('client_token', models.CharField(max_length=234)),
            ],
        ),
        migrations.CreateModel(
            name='sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Cooperativesreg',
        ),
        migrations.AddField(
            model_name='cooperative',
            name='Cooperativesector',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperative',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperative',
            name='leaderphone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperative',
            name='password1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperative',
            name='password2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='farmercode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profilecooperative',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=' cooperative Logo'),
        ),
        migrations.AddField(
            model_name='sites',
            name='Cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cooperative'),
        ),
    ]
