# Generated by Django 3.1.6 on 2021-03-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210310_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperative',
            name='Cooperativesector',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='district',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='harvesttype',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='leaderphone',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='password2',
        ),
        migrations.AddField(
            model_name='regfarmer',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
