# Generated by Django 3.1.6 on 2021-03-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210314_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmers',
            name='cell',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmers',
            name='sector',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
