# Generated by Django 3.1.6 on 2021-03-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210315_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmers',
            old_name='farmercode',
            new_name='code',
        ),
    ]
