# Generated by Django 3.1.6 on 2021-03-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210315_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmers',
            old_name='telephone',
            new_name='number',
        ),
    ]
