# Generated by Django 3.1.6 on 2021-03-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210315_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmers',
            name='harvesttype',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
